using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ac.Data.Migrations.Api
{
    /// <inheritdoc />
    public partial class UpdateChannelId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Смена типа in-place через USING — порядок колонок сохраняется.
            // Для пустых таблиц USING не применяется к строкам; для непустых нужна своя логика.

            migrationBuilder.DropForeignKey(
                name: "FK_Conversations_Channels_ChannelId",
                table: "Conversations");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Conversations"" ALTER COLUMN ""ChannelId"" TYPE integer USING (0);
                ALTER TABLE ""Channels"" ALTER COLUMN ""Id"" TYPE integer USING (0);
                ALTER TABLE ""Channels"" ALTER COLUMN ""Id"" ADD GENERATED BY DEFAULT AS IDENTITY;
            ");

            migrationBuilder.AddForeignKey(
                name: "FK_Conversations_Channels_ChannelId",
                table: "Conversations",
                column: "ChannelId",
                principalTable: "Channels",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Conversations_Channels_ChannelId",
                table: "Conversations");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Channels"" ALTER COLUMN ""Id"" DROP IDENTITY;
                ALTER TABLE ""Channels"" ALTER COLUMN ""Id"" TYPE uuid USING (gen_random_uuid());
                ALTER TABLE ""Conversations"" ALTER COLUMN ""ChannelId"" TYPE uuid USING (gen_random_uuid());
            ");

            migrationBuilder.AddForeignKey(
                name: "FK_Conversations_Channels_ChannelId",
                table: "Conversations",
                column: "ChannelId",
                principalTable: "Channels",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
